"""
PDF Renderer for Business Reports

Uses ReportLab to generate professional PDF reports with:
- Custom branding (logo, colors, company name)
- Headers and footers
- Tables and charts
- Multi-page layout
- Professional typography
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, Image, KeepTogether
)
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT, TA_JUSTIFY
from datetime import datetime, timezone
from typing import Dict, List, Any, Optional
import io
import logging

logger = logging.getLogger(__name__)


class PDFRenderer:
    """Renders business reports as professional PDF documents"""

    def __init__(self, branding: Optional[Dict] = None):
        """
        Initialize PDF renderer with branding configuration

        Args:
            branding: Branding config with company_name, logo_url, colors, footer_text
        """
        self.branding = branding or self._get_default_branding()
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def render(self, report_data: Dict) -> bytes:
        """
        Render report data as PDF

        Args:
            report_data: Complete report data structure from ReportEngine

        Returns:
            PDF file as bytes
        """
        logger.info(f"[FILE] Rendering PDF: {report_data['metadata']['report_name']}")

        # Create PDF in memory
        buffer = io.BytesIO()

        # Create document with letter size (8.5" x 11")
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=1*inch,
            bottomMargin=1*inch,
            title=report_data['metadata']['report_name']
        )

        # Build content
        story = []

        # Add cover page
        story.extend(self._render_cover_page(report_data))
        story.append(PageBreak())

        # Add sections
        sections = report_data.get('sections', {})

        if 'executive_summary' in sections:
            story.extend(self._render_executive_summary(sections['executive_summary']))
            story.append(PageBreak())

        if 'revenue' in sections:
            story.extend(self._render_revenue_section(sections['revenue']))
            story.append(PageBreak())

        if 'profit_loss' in sections:
            story.extend(self._render_pnl_section(sections['profit_loss']))
            story.append(PageBreak())

        if 'products' in sections:
            story.extend(self._render_products_section(sections['products']))
            story.append(PageBreak())

        if 'ads' in sections:
            story.extend(self._render_ads_section(sections['ads']))
            story.append(PageBreak())

        # Build PDF
        doc.build(
            story,
            onFirstPage=self._add_page_decorations,
            onLaterPages=self._add_page_decorations
        )

        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()

        logger.info(f"[SUCCESS] PDF rendered: {len(pdf_bytes) / 1024:.1f} KB")
        return pdf_bytes

    # ==================== Page Decorations ====================

    def _add_page_decorations(self, canvas, doc):
        """Add header and footer to each page"""
        canvas.saveState()

        # Header
        canvas.setFont('Helvetica-Bold', 10)
        canvas.setFillColor(colors.HexColor(self.branding['primary_color']))
        canvas.drawString(
            0.75*inch,
            doc.height + 1.5*inch,
            self.branding['company_name']
        )

        # Footer
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(
            doc.width / 2 + 0.75*inch,
            0.5*inch,
            self.branding.get('footer_text', 'Generated by Ospra Intelligence')
        )

        # Page number
        canvas.drawRightString(
            doc.width + 0.75*inch,
            0.5*inch,
            f"Page {doc.page}"
        )

        canvas.restoreState()

    # ==================== Cover Page ====================

    def _render_cover_page(self, report_data: Dict) -> List:
        """Render report cover page"""
        elements = []
        metadata = report_data['metadata']

        # Add spacing from top
        elements.append(Spacer(1, 2*inch))

        # Report title
        title = Paragraph(
            metadata['report_name'],
            self.styles['CustomTitle']
        )
        elements.append(title)
        elements.append(Spacer(1, 0.3*inch))

        # Company name
        company = Paragraph(
            self.branding['company_name'],
            self.styles['CustomSubtitle']
        )
        elements.append(company)
        elements.append(Spacer(1, 0.5*inch))

        # Date range
        date_range = report_data['metadata'].get('date_range', {})
        date_text = self._format_date_range(date_range)

        date_para = Paragraph(
            f"<b>Period:</b> {date_text}",
            self.styles['CustomNormal']
        )
        elements.append(date_para)
        elements.append(Spacer(1, 0.2*inch))

        # Generated date
        generated_para = Paragraph(
            f"<b>Generated:</b> {datetime.now(timezone.utc).strftime('%B %d, %Y at %I:%M %p UTC')}",
            self.styles['CustomNormal']
        )
        elements.append(generated_para)

        return elements

    # ==================== Executive Summary ====================

    def _render_executive_summary(self, data: Dict) -> List:
        """Render executive summary section"""
        elements = []

        # Section title
        elements.append(Paragraph("Executive Summary", self.styles['CustomHeading1']))
        elements.append(Spacer(1, 0.3*inch))

        # Key Metrics Table
        elements.append(Paragraph("Key Metrics", self.styles['CustomHeading2']))
        elements.append(Spacer(1, 0.2*inch))

        metrics = data['key_metrics']

        # Create metrics table
        table_data = [
            ['Metric', 'Current', 'Previous', 'Change'],
            [
                'Revenue',
                f"${metrics['revenue']['value']:,.2f}",
                f"${metrics['revenue']['previous']:,.2f}",
                self._format_change(metrics['revenue']['change_percent'])
            ],
            [
                'Orders',
                f"{metrics['orders']['value']:,}",
                f"{metrics['orders']['previous']:,}",
                self._format_change(metrics['orders']['change_percent'])
            ],
            [
                'Profit',
                f"${metrics['profit']['value']:,.2f}",
                f"{metrics['profit']['margin_percent']:.1f}% margin",
                self._format_change(metrics['profit']['change_percent'])
            ],
            [
                'ROI / ROAS',
                f"{metrics['roi']['value']:.2f}x / {metrics['roi']['roas']:.2f}x",
                '-',
                '-'
            ]
        ]

        table = Table(table_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(self.branding['primary_color'])),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 0.4*inch))

        # Highlights
        if data.get('highlights'):
            elements.append(Paragraph("Highlights", self.styles['CustomHeading2']))
            elements.append(Spacer(1, 0.1*inch))

            for highlight in data['highlights']:
                bullet = Paragraph(f"• {highlight}", self.styles['CustomBullet'])
                elements.append(bullet)
                elements.append(Spacer(1, 0.05*inch))

            elements.append(Spacer(1, 0.2*inch))

        # Concerns
        if data.get('concerns'):
            elements.append(Paragraph("Areas of Concern", self.styles['CustomHeading2']))
            elements.append(Spacer(1, 0.1*inch))

            for concern in data['concerns']:
                bullet = Paragraph(f"[WARNING] {concern}", self.styles['CustomBullet'])
                elements.append(bullet)
                elements.append(Spacer(1, 0.05*inch))

            elements.append(Spacer(1, 0.2*inch))

        # Recommendations
        if data.get('recommendations'):
            elements.append(Paragraph("Recommendations", self.styles['CustomHeading2']))
            elements.append(Spacer(1, 0.1*inch))

            for rec in data['recommendations']:
                bullet = Paragraph(f"→ {rec}", self.styles['CustomBullet'])
                elements.append(bullet)
                elements.append(Spacer(1, 0.05*inch))

        return elements

    # ==================== Revenue Section ====================

    def _render_revenue_section(self, data: Dict) -> List:
        """Render revenue analysis section"""
        elements = []

        elements.append(Paragraph("Revenue Analysis", self.styles['CustomHeading1']))
        elements.append(Spacer(1, 0.3*inch))

        # Total revenue
        elements.append(Paragraph(
            f"Total Revenue: <b>${data.get('total_revenue', 0):,.2f}</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.1*inch))

        elements.append(Paragraph(
            f"Growth Rate: <b>{data.get('revenue_growth_rate', 0):.1f}%</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.1*inch))

        elements.append(Paragraph(
            f"Projected Monthly: <b>${data.get('projected_monthly', 0):,.2f}</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.3*inch))

        # TODO: Add revenue charts
        # TODO: Add top revenue products table

        return elements

    # ==================== P&L Section ====================

    def _render_pnl_section(self, data: Dict) -> List:
        """Render Profit & Loss section"""
        elements = []

        elements.append(Paragraph("Profit & Loss Statement", self.styles['CustomHeading1']))
        elements.append(Spacer(1, 0.3*inch))

        # P&L Table
        costs = data.get('costs', {})

        table_data = [
            ['Item', 'Amount'],
            ['Gross Revenue', f"${data.get('gross_revenue', 0):,.2f}"],
            ['', ''],
            ['Costs', ''],
            ['  Product Costs', f"${costs.get('products', 0):,.2f}"],
            ['  Advertising', f"${costs.get('advertising', 0):,.2f}"],
            ['  Platform Fees', f"${costs.get('platform_fees', 0):,.2f}"],
            ['  Shipping', f"${costs.get('shipping', 0):,.2f}"],
            ['  Other', f"${costs.get('other', 0):,.2f}"],
            ['Total Costs', f"${costs.get('total', 0):,.2f}"],
            ['', ''],
            ['Net Profit', f"${data.get('net_profit', 0):,.2f}"],
            ['Profit Margin', f"{data.get('profit_margin_percent', 0):.1f}%"],
        ]

        table = Table(table_data, colWidths=[4*inch, 2*inch])
        table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTNAME', (0, -2), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('LINEABOVE', (0, -2), (-1, -2), 2, colors.black),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))

        elements.append(table)

        return elements

    # ==================== Products Section ====================

    def _render_products_section(self, data: Dict) -> List:
        """Render product performance section"""
        elements = []

        elements.append(Paragraph("Product Performance", self.styles['CustomHeading1']))
        elements.append(Spacer(1, 0.3*inch))

        # Top performers
        elements.append(Paragraph("Top Performers", self.styles['CustomHeading2']))
        elements.append(Spacer(1, 0.2*inch))

        # TODO: Add product tables and charts
        elements.append(Paragraph(
            "Product performance data will be populated from analytics engine",
            self.styles['CustomNormal']
        ))

        return elements

    # ==================== Ads Section ====================

    def _render_ads_section(self, data: Dict) -> List:
        """Render advertising performance section"""
        elements = []

        elements.append(Paragraph("Advertising Performance", self.styles['CustomHeading1']))
        elements.append(Spacer(1, 0.3*inch))

        # Overall metrics
        elements.append(Paragraph(
            f"Total Spend: <b>${data.get('total_spend', 0):,.2f}</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.1*inch))

        elements.append(Paragraph(
            f"Total Revenue: <b>${data.get('total_revenue', 0):,.2f}</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.1*inch))

        elements.append(Paragraph(
            f"Overall ROAS: <b>{data.get('overall_roas', 0):.2f}x</b>",
            self.styles['CustomNormal']
        ))
        elements.append(Spacer(1, 0.3*inch))

        # By platform table
        elements.append(Paragraph("Performance by Platform", self.styles['CustomHeading2']))
        elements.append(Spacer(1, 0.2*inch))

        by_platform = data.get('by_platform', {})

        table_data = [
            ['Platform', 'Spend', 'Revenue', 'ROAS'],
            [
                'Facebook',
                f"${by_platform.get('facebook', {}).get('spend', 0):,.2f}",
                f"${by_platform.get('facebook', {}).get('revenue', 0):,.2f}",
                f"{by_platform.get('facebook', {}).get('roas', 0):.2f}x"
            ],
            [
                'Google',
                f"${by_platform.get('google', {}).get('spend', 0):,.2f}",
                f"${by_platform.get('google', {}).get('revenue', 0):,.2f}",
                f"{by_platform.get('google', {}).get('roas', 0):.2f}x"
            ],
            [
                'TikTok',
                f"${by_platform.get('tiktok', {}).get('spend', 0):,.2f}",
                f"${by_platform.get('tiktok', {}).get('revenue', 0):,.2f}",
                f"{by_platform.get('tiktok', {}).get('roas', 0):.2f}x"
            ],
        ]

        table = Table(table_data, colWidths=[2*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor(self.branding['primary_color'])),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ]))

        elements.append(table)

        return elements

    # ==================== Helper Methods ====================

    def _setup_custom_styles(self):
        """Setup custom paragraph styles"""

        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=32,
            textColor=colors.HexColor(self.branding['primary_color']),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))

        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=18,
            textColor=colors.HexColor(self.branding['secondary_color']),
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))

        # Heading 1
        self.styles.add(ParagraphStyle(
            name='CustomHeading1',
            parent=self.styles['Heading1'],
            fontSize=20,
            textColor=colors.HexColor(self.branding['primary_color']),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        ))

        # Heading 2
        self.styles.add(ParagraphStyle(
            name='CustomHeading2',
            parent=self.styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor(self.branding['secondary_color']),
            spaceAfter=6,
            fontName='Helvetica-Bold'
        ))

        # Normal text
        self.styles.add(ParagraphStyle(
            name='CustomNormal',
            parent=self.styles['Normal'],
            fontSize=11,
            leading=14,
            alignment=TA_LEFT
        ))

        # Bullet points
        self.styles.add(ParagraphStyle(
            name='CustomBullet',
            parent=self.styles['Normal'],
            fontSize=10,
            leading=13,
            leftIndent=20,
            spaceBefore=3,
            spaceAfter=3
        ))

    def _format_change(self, change_percent: float) -> str:
        """Format percentage change with color indicator"""
        if change_percent > 0:
            return f"+{change_percent:.1f}%"
        elif change_percent < 0:
            return f"{change_percent:.1f}%"
        else:
            return "0.0%"

    def _format_date_range(self, date_range: Dict) -> str:
        """Format date range for display"""
        if date_range.get('type') == 'relative':
            value = date_range.get('value', 'last_7_days')
            return value.replace('_', ' ').title()
        else:
            start = date_range.get('start', 'N/A')
            end = date_range.get('end', 'N/A')
            return f"{start} to {end}"

    def _get_default_branding(self) -> Dict:
        """Get default branding configuration"""
        return {
            'company_name': 'Oubon Shop',
            'primary_color': '#3b82f6',
            'secondary_color': '#10b981',
            'footer_text': 'Generated by Ospra Intelligence'
        }


# Export singleton instance creator
def create_pdf_renderer(branding: Optional[Dict] = None) -> PDFRenderer:
    """Create a PDF renderer instance with branding"""
    return PDFRenderer(branding)
