/**
 * Action Queue Panel - Oi's Proposed Actions
 * 
 * Displays AI-proposed actions for the user to:
 * - Accept (execute with one click)
 * - Decline (AI learns from rejection)
 * - View details before deciding
 * 
 * Actions are generated by Oi based on:
 * - Product discovery
 * - Ad performance analysis
 * - Price monitoring
 * - Inventory alerts
 * 
 * @author OspraOS
 * @date December 2024
 */

import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Zap,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  Loader2,
  Package,
  TrendingUp,
  DollarSign,
  AlertTriangle,
  Clock,
  Sparkles,
  RefreshCw,
  Filter,
  CheckCircle2,
  XCircle,
  ShoppingCart,
  PauseCircle,
  BarChart3,
  Percent,
  Brain
} from 'lucide-react';

// Types
interface AIAction {
  action_id: string;
  action_type: string;
  title: string;
  description: string;
  impact_summary: string;
  parameters: Record<string, unknown>;
  confidence: number;
  status: 'pending' | 'accepted' | 'declined' | 'executing' | 'completed' | 'failed';
  created_at: string;
  expires_at: string;
}

interface ActionQueuePanelProps {
  isOpen: boolean;
  onClose: () => void;
}

// API
const apiBaseUrl = import.meta.env.VITE_API_URL || 'http://localhost:8000';

// Action type icons
const ACTION_ICONS: Record<string, React.ReactNode> = {
  deploy_product: <Package className="w-4 h-4" />,
  pause_ad: <PauseCircle className="w-4 h-4" />,
  increase_ad_budget: <TrendingUp className="w-4 h-4" />,
  decrease_ad_budget: <TrendingUp className="w-4 h-4 rotate-180" />,
  adjust_price: <DollarSign className="w-4 h-4" />,
  reorder_inventory: <ShoppingCart className="w-4 h-4" />,
  create_ad_campaign: <BarChart3 className="w-4 h-4" />,
  update_product_description: <Sparkles className="w-4 h-4" />,
};

// Action type colors
const ACTION_COLORS: Record<string, string> = {
  deploy_product: 'from-emerald-500 to-cyan-500',
  pause_ad: 'from-amber-500 to-orange-500',
  increase_ad_budget: 'from-green-500 to-emerald-500',
  decrease_ad_budget: 'from-red-500 to-orange-500',
  adjust_price: 'from-blue-500 to-indigo-500',
  reorder_inventory: 'from-purple-500 to-pink-500',
  create_ad_campaign: 'from-cyan-500 to-blue-500',
  update_product_description: 'from-violet-500 to-purple-500',
};

// Confidence indicator
const ConfidenceIndicator: React.FC<{ confidence: number }> = ({ confidence }) => {
  const percent = Math.round(confidence * 100);
  const color = percent >= 80 ? 'text-emerald-400' : percent >= 60 ? 'text-amber-400' : 'text-red-400';
  const bgColor = percent >= 80 ? 'bg-emerald-500/20' : percent >= 60 ? 'bg-amber-500/20' : 'bg-red-500/20';
  
  return (
    <div className={`flex items-center gap-1.5 px-2 py-1 rounded-full ${bgColor}`}>
      <Percent className={`w-3 h-3 ${color}`} />
      <span className={`text-xs font-medium ${color}`}>{percent}%</span>
    </div>
  );
};

// Time remaining
const TimeRemaining: React.FC<{ expiresAt: string }> = ({ expiresAt }) => {
  const [remaining, setRemaining] = useState('');
  
  useEffect(() => {
    const update = () => {
      const now = new Date();
      const expires = new Date(expiresAt);
      const diff = expires.getTime() - now.getTime();
      
      if (diff <= 0) {
        setRemaining('Expired');
        return;
      }
      
      const hours = Math.floor(diff / (1000 * 60 * 60));
      const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
      
      if (hours > 24) {
        const days = Math.floor(hours / 24);
        setRemaining(`${days}d remaining`);
      } else if (hours > 0) {
        setRemaining(`${hours}h ${minutes}m remaining`);
      } else {
        setRemaining(`${minutes}m remaining`);
      }
    };
    
    update();
    const interval = setInterval(update, 60000);
    return () => clearInterval(interval);
  }, [expiresAt]);
  
  const isUrgent = remaining.includes('m remaining') && !remaining.includes('h');
  
  return (
    <div className={`flex items-center gap-1 text-xs ${isUrgent ? 'text-amber-400' : 'text-white/40'}`}>
      <Clock className="w-3 h-3" />
      <span>{remaining}</span>
    </div>
  );
};

// Single action card
const ActionCard: React.FC<{
  action: AIAction;
  onAccept: (id: string) => void;
  onDecline: (id: string, reason?: string) => void;
  isProcessing: boolean;
}> = ({ action, onAccept, onDecline, isProcessing }) => {
  const [expanded, setExpanded] = useState(false);
  const [showDeclineReason, setShowDeclineReason] = useState(false);
  const [declineReason, setDeclineReason] = useState('');
  
  const icon = ACTION_ICONS[action.action_type] || <Zap className="w-4 h-4" />;
  const colorGradient = ACTION_COLORS[action.action_type] || 'from-gray-500 to-gray-600';
  
  const handleDecline = () => {
    if (showDeclineReason) {
      onDecline(action.action_id, declineReason || undefined);
      setShowDeclineReason(false);
      setDeclineReason('');
    } else {
      setShowDeclineReason(true);
    }
  };
  
  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl overflow-hidden"
    >
      {/* Main content */}
      <div className="p-4">
        <div className="flex items-start gap-3">
          {/* Icon */}
          <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${colorGradient} flex items-center justify-center flex-shrink-0`}>
            {icon}
          </div>
          
          {/* Content */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <h4 className="text-white font-medium truncate">{action.title}</h4>
              <ConfidenceIndicator confidence={action.confidence} />
            </div>
            
            <p className="text-sm text-white/60 line-clamp-2">{action.description}</p>
            
            {/* Impact summary */}
            <div className="mt-2 flex items-center gap-2 text-xs text-emerald-400">
              <TrendingUp className="w-3 h-3" />
              <span>{action.impact_summary}</span>
            </div>
            
            {/* Time remaining */}
            <div className="mt-2">
              <TimeRemaining expiresAt={action.expires_at} />
            </div>
          </div>
          
          {/* Expand toggle */}
          <button
            onClick={() => setExpanded(!expanded)}
            className="p-2 rounded-lg hover:bg-white/10 text-white/50 transition-colors"
          >
            {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </button>
        </div>
        
        {/* Expanded details */}
        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden"
            >
              <div className="mt-4 pt-4 border-t border-white/10">
                <h5 className="text-xs text-white/40 uppercase tracking-wider mb-2">Parameters</h5>
                <div className="bg-black/20 rounded-lg p-3 text-xs font-mono text-white/70 overflow-x-auto">
                  <pre>{JSON.stringify(action.parameters, null, 2)}</pre>
                </div>
                
                <div className="mt-3 flex items-center gap-2 text-xs text-white/40">
                  <span>Created: {new Date(action.created_at).toLocaleString()}</span>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
        
        {/* Decline reason input */}
        <AnimatePresence>
          {showDeclineReason && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              className="overflow-hidden"
            >
              <div className="mt-4 pt-4 border-t border-white/10">
                <input
                  type="text"
                  value={declineReason}
                  onChange={(e) => setDeclineReason(e.target.value)}
                  placeholder="Why are you declining? (optional, helps Oi learn)"
                  className="w-full px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm placeholder-white/30 focus:outline-none focus:border-white/20"
                />
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
      
      {/* Action buttons */}
      <div className="flex border-t border-white/10">
        <button
          onClick={handleDecline}
          disabled={isProcessing}
          className="flex-1 px-4 py-3 flex items-center justify-center gap-2 text-red-400 hover:bg-red-500/10 transition-colors disabled:opacity-50"
        >
          <X className="w-4 h-4" />
          <span className="text-sm">{showDeclineReason ? 'Confirm Decline' : 'Decline'}</span>
        </button>
        
        <div className="w-px bg-white/10" />
        
        <button
          onClick={() => onAccept(action.action_id)}
          disabled={isProcessing}
          className="flex-1 px-4 py-3 flex items-center justify-center gap-2 text-emerald-400 hover:bg-emerald-500/10 transition-colors disabled:opacity-50"
        >
          {isProcessing ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Check className="w-4 h-4" />
          )}
          <span className="text-sm">Accept & Execute</span>
        </button>
      </div>
    </motion.div>
  );
};

// Empty state
const EmptyState: React.FC = () => (
  <div className="flex flex-col items-center justify-center py-12 px-6 text-center">
    <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center mb-4">
      <CheckCircle2 className="w-8 h-8 text-emerald-400" />
    </div>
    <h3 className="text-white font-medium mb-2">All caught up!</h3>
    <p className="text-white/50 text-sm max-w-xs">
      Oi doesn't have any actions for you right now. New recommendations will appear as opportunities are discovered.
    </p>
  </div>
);

// Stats summary
const StatsSummary: React.FC<{ stats: Record<string, unknown> }> = ({ stats }) => {
  if (!stats || Object.keys(stats).length === 0) return null;
  
  return (
    <div className="grid grid-cols-3 gap-2 p-4 bg-white/5 rounded-xl">
      <div className="text-center">
        <div className="text-2xl font-bold text-white">{String(stats.total_proposed || 0)}</div>
        <div className="text-xs text-white/40">Proposed</div>
      </div>
      <div className="text-center">
        <div className="text-2xl font-bold text-emerald-400">{String(stats.total_accepted || 0)}</div>
        <div className="text-xs text-white/40">Accepted</div>
      </div>
      <div className="text-center">
        <div className="text-2xl font-bold text-amber-400">{String(stats.total_declined || 0)}</div>
        <div className="text-xs text-white/40">Declined</div>
      </div>
    </div>
  );
};

// Main component
export const ActionQueuePanel: React.FC<ActionQueuePanelProps> = ({ isOpen, onClose }) => {
  const [actions, setActions] = useState<AIAction[]>([]);
  const [stats, setStats] = useState<Record<string, unknown>>({});
  const [isLoading, setIsLoading] = useState(true);
  const [processingId, setProcessingId] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | 'high_confidence'>('all');
  const [error, setError] = useState<string | null>(null);
  
  // Fetch actions
  const fetchActions = useCallback(async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      const minConfidence = filter === 'high_confidence' ? 0.8 : 0.5;
      const response = await fetch(`${apiBaseUrl}/api/ai/actions?min_confidence=${minConfidence}`);
      
      if (!response.ok) throw new Error('Failed to fetch actions');
      
      const data = await response.json();
      setActions(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load actions');
      setActions([]);
    } finally {
      setIsLoading(false);
    }
  }, [filter]);
  
  // Fetch stats
  const fetchStats = useCallback(async () => {
    try {
      const response = await fetch(`${apiBaseUrl}/api/ai/actions/stats/summary`);
      if (response.ok) {
        const data = await response.json();
        setStats(data);
      }
    } catch {
      // Stats are optional
    }
  }, []);
  
  // Load data when opened
  useEffect(() => {
    if (isOpen) {
      fetchActions();
      fetchStats();
    }
  }, [isOpen, fetchActions, fetchStats]);
  
  // Accept action
  const handleAccept = async (actionId: string) => {
    try {
      setProcessingId(actionId);
      
      const response = await fetch(`${apiBaseUrl}/api/ai/actions/${actionId}/accept`, {
        method: 'POST',
      });
      
      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.detail || 'Failed to execute action');
      }
      
      // Remove from list
      setActions(prev => prev.filter(a => a.action_id !== actionId));
      
      // Refresh stats
      fetchStats();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to accept action');
    } finally {
      setProcessingId(null);
    }
  };
  
  // Decline action
  const handleDecline = async (actionId: string, reason?: string) => {
    try {
      setProcessingId(actionId);
      
      const response = await fetch(`${apiBaseUrl}/api/ai/actions/${actionId}/decline`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason }),
      });
      
      if (!response.ok) throw new Error('Failed to decline action');
      
      // Remove from list
      setActions(prev => prev.filter(a => a.action_id !== actionId));
      
      // Refresh stats
      fetchStats();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to decline action');
    } finally {
      setProcessingId(null);
    }
  };
  
  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/40 backdrop-blur-sm z-40"
          />
          
          {/* Panel */}
          <motion.div
            initial={{ opacity: 0, x: 100 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 100 }}
            transition={{ type: 'spring', damping: 25 }}
            className="fixed right-4 top-20 bottom-20 w-[480px] z-50 bg-gradient-to-br from-slate-900/95 via-slate-800/95 to-slate-900/95 backdrop-blur-2xl border border-white/10 rounded-3xl flex flex-col overflow-hidden shadow-2xl"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-white/10">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-violet-500 to-purple-600 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h3 className="text-white font-semibold">Action Queue</h3>
                  <p className="text-xs text-white/50">
                    {actions.length} pending action{actions.length !== 1 ? 's' : ''}
                  </p>
                </div>
              </div>
              
              <div className="flex items-center gap-2">
                <button
                  onClick={fetchActions}
                  className="p-2 rounded-xl hover:bg-white/10 text-white/50 hover:text-white transition-colors"
                  title="Refresh"
                >
                  <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
                </button>
                <button
                  onClick={onClose}
                  className="p-2 rounded-xl hover:bg-white/10 text-white/50 hover:text-white transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>
            
            {/* Filter */}
            <div className="px-5 py-3 border-b border-white/10">
              <div className="flex items-center gap-2">
                <Filter className="w-4 h-4 text-white/40" />
                <select
                  value={filter}
                  onChange={(e) => setFilter(e.target.value as 'all' | 'high_confidence')}
                  className="bg-white/5 border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white focus:outline-none focus:border-white/20"
                >
                  <option value="all">All Actions</option>
                  <option value="high_confidence">High Confidence Only (80%+)</option>
                </select>
              </div>
            </div>
            
            {/* Stats */}
            <div className="px-5 py-3">
              <StatsSummary stats={stats} />
            </div>
            
            {/* Error */}
            {error && (
              <div className="mx-5 mb-3 p-3 bg-red-500/10 border border-red-500/20 rounded-lg">
                <div className="flex items-center gap-2 text-red-400 text-sm">
                  <AlertTriangle className="w-4 h-4" />
                  <span>{error}</span>
                </div>
              </div>
            )}
            
            {/* Actions list */}
            <div className="flex-1 overflow-y-auto px-5 py-3 space-y-3">
              {isLoading ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-8 h-8 text-white/50 animate-spin" />
                </div>
              ) : actions.length === 0 ? (
                <EmptyState />
              ) : (
                <AnimatePresence mode="popLayout">
                  {actions.map((action) => (
                    <ActionCard
                      key={action.action_id}
                      action={action}
                      onAccept={handleAccept}
                      onDecline={handleDecline}
                      isProcessing={processingId === action.action_id}
                    />
                  ))}
                </AnimatePresence>
              )}
            </div>
            
            {/* Footer */}
            <div className="px-5 py-3 border-t border-white/10">
              <p className="text-xs text-white/30 text-center">
                Oi learns from your decisions to improve future recommendations
              </p>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};

// Floating action queue button (shows count)
export const ActionQueueButton: React.FC<{ 
  onClick: () => void; 
  count: number;
}> = ({ onClick, count }) => {
  if (count === 0) return null;
  
  return (
    <motion.button
      initial={{ scale: 0 }}
      animate={{ scale: 1 }}
      exit={{ scale: 0 }}
      whileHover={{ scale: 1.05 }}
      whileTap={{ scale: 0.95 }}
      onClick={onClick}
      className="fixed bottom-6 right-24 z-30 flex items-center gap-2 px-4 py-3 rounded-2xl bg-gradient-to-r from-violet-500 to-purple-600 shadow-lg shadow-purple-500/30 text-white"
    >
      <Zap className="w-5 h-5" />
      <span className="font-medium">{count} Actions</span>
      <span className="w-2 h-2 bg-white rounded-full animate-pulse" />
    </motion.button>
  );
};

export default ActionQueuePanel;
