"""
Report API Routes

Endpoints:
- POST /api/reports/generate - Generate report on demand
- GET /api/reports/templates - List available templates
- GET /api/reports/history - View report history
- POST /api/reports/schedules - Create scheduled report
- GET /api/reports/schedules - List schedules
"""
from fastapi import APIRouter, HTTPException, BackgroundTasks
from fastapi.responses import Response
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
import logging
import uuid
import os

from ospra_os.reports.report_engine import get_report_engine
from ospra_os.reports.renderers.pdf_renderer import create_pdf_renderer

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/reports", tags=["reports"])


# ==================== Request Models ====================

class DateRangeConfig(BaseModel):
    type: str = Field(default="relative", description="relative or absolute")
    value: Optional[str] = Field(default="last_7_days", description="e.g. last_7_days, last_30_days")
    start: Optional[str] = None
    end: Optional[str] = None


class ReportFilters(BaseModel):
    date_range: DateRangeConfig = DateRangeConfig()
    stores: Optional[List[str]] = None
    products: Optional[str] = "all"
    categories: Optional[List[str]] = None


class BrandingConfig(BaseModel):
    company_name: str = "Oubon Shop"
    logo_url: Optional[str] = None
    primary_color: str = "#3b82f6"
    secondary_color: str = "#10b981"
    footer_text: str = "Generated by Ospra Intelligence"


class GenerateReportRequest(BaseModel):
    name: str = Field(..., description="Report name")
    report_type: str = Field(default="executive", description="executive, revenue, full, etc.")
    sections: List[str] = Field(default=["executive_summary"], description="Sections to include")
    filters: ReportFilters = ReportFilters()
    branding: Optional[BrandingConfig] = None
    format: str = Field(default="json", description="json, pdf, html, csv")


class CreateScheduleRequest(BaseModel):
    name: str
    report_config: GenerateReportRequest
    frequency: str = Field(..., description="daily, weekly, monthly")
    day_of_week: Optional[int] = None  # 0-6 for weekly
    day_of_month: Optional[int] = None  # 1-31 for monthly
    time: str = Field(..., description="HH:MM format")
    timezone: str = "UTC"
    recipients: Dict[str, Any] = Field(default_factory=dict)


# ==================== Response Models ====================

class ReportMetadata(BaseModel):
    report_id: str
    name: str
    generated_at: str
    generation_time_ms: int
    format: str
    size_kb: Optional[int] = None


class TemplateInfo(BaseModel):
    template_id: str
    name: str
    description: str
    report_type: str
    sections: List[str]
    is_system: bool


# ==================== Endpoints ====================

@router.post("/generate")
async def generate_report(request: GenerateReportRequest):
    """
    Generate a report on demand

    Returns the report data (JSON by default) or download URL for PDF
    """
    try:
        logger.info(f"[FILE] Generating report: {request.name}")

        # Get report engine
        engine = get_report_engine()

        # Build config
        config = {
            'name': request.name,
            'report_type': request.report_type,
            'sections': request.sections,
            'filters': request.filters.dict(),
            'branding': request.branding.dict() if request.branding else None
        }

        # Generate report data
        report_data = await engine.generate_report(config)

        # Return based on format
        if request.format == 'json':
            return {
                'success': True,
                'report_id': f"rpt_{uuid.uuid4().hex[:12]}",
                'data': report_data
            }
        elif request.format == 'pdf':
            # Render as PDF
            logger.info("[FILE] Rendering report as PDF...")
            pdf_renderer = create_pdf_renderer(request.branding.dict() if request.branding else None)
            pdf_bytes = pdf_renderer.render(report_data)

            # Save to disk for persistence (optional)
            report_id = f"rpt_{uuid.uuid4().hex[:12]}"
            os.makedirs('data/reports', exist_ok=True)
            pdf_path = f"data/reports/{report_id}.pdf"

            with open(pdf_path, 'wb') as f:
                f.write(pdf_bytes)

            logger.info(f"[SUCCESS] PDF saved to {pdf_path}")

            # Return PDF as downloadable file
            return Response(
                content=pdf_bytes,
                media_type='application/pdf',
                headers={
                    'Content-Disposition': f'attachment; filename="{request.name.replace(" ", "_")}.pdf"'
                }
            )
        else:
            return {
                'success': True,
                'report_id': f"rpt_{uuid.uuid4().hex[:12]}",
                'data': report_data
            }

    except Exception as e:
        logger.error(f"[ERROR] Report generation failed: {e}")
        raise HTTPException(status_code=500, detail="Report generation failed. Please try again.")


@router.get("/templates")
async def list_templates():
    """
    List available report templates

    Returns system and user-created templates
    """
    templates = [
        {
            'template_id': 'tpl_executive',
            'name': 'Executive Summary',
            'description': 'High-level business overview with key metrics',
            'report_type': 'executive',
            'sections': ['executive_summary'],
            'is_system': True,
            'icon': '[STATS]'
        },
        {
            'template_id': 'tpl_weekly_summary',
            'name': 'Weekly Business Summary',
            'description': 'Comprehensive weekly report with all key sections',
            'report_type': 'full',
            'sections': ['executive_summary', 'revenue', 'products', 'ads'],
            'is_system': True,
            'icon': '[TREND]'
        },
        {
            'template_id': 'tpl_revenue',
            'name': 'Revenue Report',
            'description': 'Detailed revenue analysis and breakdown',
            'report_type': 'revenue',
            'sections': ['revenue'],
            'is_system': True,
            'icon': '[PRICE]'
        },
        {
            'template_id': 'tpl_product',
            'name': 'Product Performance',
            'description': 'Product-level performance and recommendations',
            'report_type': 'product',
            'sections': ['products'],
            'is_system': True,
            'icon': '[PACKAGE]'
        },
        {
            'template_id': 'tpl_ads',
            'name': 'Ad Performance',
            'description': 'Advertising metrics and campaign analysis',
            'report_type': 'ad',
            'sections': ['ads'],
            'is_system': True,
            'icon': ''
        },
        {
            'template_id': 'tpl_pnl',
            'name': 'Profit & Loss',
            'description': 'P&L statement with cost breakdown',
            'report_type': 'pnl',
            'sections': ['profit_loss'],
            'is_system': True,
            'icon': '[MONEY]'
        }
    ]

    return {
        'success': True,
        'templates': templates
    }


@router.get("/templates/{template_id}")
async def get_template(template_id: str):
    """Get template details and default configuration"""
    # TODO: Fetch from database
    templates = await list_templates()

    template = next((t for t in templates['templates'] if t['template_id'] == template_id), None)

    if not template:
        raise HTTPException(status_code=404, detail="Template not found")

    return {
        'success': True,
        'template': template
    }


@router.get("/history")
async def get_report_history(
    limit: int = 20,
    offset: int = 0,
    report_type: Optional[str] = None
):
    """
    Get history of generated reports

    Query params:
    - limit: Number of reports to return
    - offset: Pagination offset
    - report_type: Filter by type (executive, revenue, etc.)
    """
    # TODO: Fetch from database
    # For now, return mock data

    history = [
        {
            'report_id': 'rpt_abc123',
            'name': 'Weekly Business Summary',
            'report_type': 'full',
            'generated_at': datetime.now(timezone.utc).isoformat(),
            'date_range': 'Nov 13-19, 2025',
            'format': 'pdf',
            'size_kb': 1250,
            'generated_by': 'schedule_weekly',
            'download_url': '/api/reports/rpt_abc123/download'
        }
    ]

    return {
        'success': True,
        'total': len(history),
        'reports': history
    }


@router.get("/{report_id}")
async def get_report(report_id: str):
    """Get specific report metadata and download URL"""
    # TODO: Fetch from database

    return {
        'success': True,
        'report': {
            'report_id': report_id,
            'name': 'Weekly Business Summary',
            'generated_at': datetime.now(timezone.utc).isoformat(),
            'download_url': f'/api/reports/{report_id}/download'
        }
    }


@router.delete("/{report_id}")
async def delete_report(report_id: str):
    """Delete a report"""
    # TODO: Implement soft delete in database

    return {
        'success': True,
        'message': 'Report deleted successfully'
    }


# ==================== Scheduling Endpoints ====================

@router.post("/schedules")
async def create_schedule(request: CreateScheduleRequest):
    """Create a new scheduled report"""
    try:
        schedule_id = f"sched_{uuid.uuid4().hex[:12]}"

        # TODO: Save to database
        # TODO: Calculate next_run based on frequency

        logger.info(f"[SUCCESS] Created schedule: {schedule_id}")

        return {
            'success': True,
            'schedule_id': schedule_id,
            'message': 'Schedule created successfully'
        }

    except Exception as e:
        logger.error(f"[ERROR] Failed to create schedule: {e}")
        raise HTTPException(status_code=500, detail="Failed to create schedule. Please try again.")


@router.get("/schedules")
async def list_schedules(active_only: bool = True):
    """List all scheduled reports"""
    # TODO: Fetch from database

    schedules = [
        {
            'schedule_id': 'sched_abc123',
            'name': 'Weekly Business Summary',
            'frequency': 'weekly',
            'day_of_week': 1,  # Monday
            'time': '08:00',
            'timezone': 'America/Los_Angeles',
            'is_active': True,
            'next_run': datetime.now(timezone.utc).isoformat(),
            'last_run': None,
            'total_runs': 0
        }
    ]

    return {
        'success': True,
        'schedules': schedules
    }


@router.get("/schedules/{schedule_id}")
async def get_schedule(schedule_id: str):
    """Get schedule details"""
    # TODO: Fetch from database

    return {
        'success': True,
        'schedule': {
            'schedule_id': schedule_id,
            'name': 'Weekly Business Summary',
            'is_active': True
        }
    }


@router.put("/schedules/{schedule_id}")
async def update_schedule(schedule_id: str, updates: Dict):
    """Update schedule"""
    # TODO: Update in database

    return {
        'success': True,
        'message': 'Schedule updated successfully'
    }


@router.delete("/schedules/{schedule_id}")
async def delete_schedule(schedule_id: str):
    """Delete a schedule"""
    # TODO: Delete from database

    return {
        'success': True,
        'message': 'Schedule deleted successfully'
    }


@router.post("/schedules/{schedule_id}/run")
async def run_schedule(schedule_id: str, background_tasks: BackgroundTasks):
    """Manually trigger a scheduled report"""
    # TODO: Fetch schedule config and generate report

    return {
        'success': True,
        'message': 'Report generation started'
    }


logger.info("[SUCCESS] Report routes loaded successfully")
