"""
Account-management API routes — Data & Privacy.

Powers the **Settings → Data & Privacy** section of the app:

- ``GET  /api/account/data-export``   — download everything we hold for the
  signed-in user (mirrors the ``customers/data_request`` GDPR webhook).
- ``POST /api/account/data-delete``   — wipe the signed-in user's data and
  optionally also delete their connected stores (mirrors the
  ``customers/redact`` + ``shop/redact`` webhooks).
- ``GET  /api/account/data-summary``  — short JSON the UI shows above the
  buttons ("you have N orders, M follow-ups stored, K connected stores")
  so users know what they're about to download or delete.

Why a thin route around ``ospra_os.security.gdpr``: that module is the
single source of truth for the actual data plumbing — the GDPR webhooks
hit the same functions. Keeping the auth + tenancy gating in this route
means ``gdpr.py`` can stay free of FastAPI / JWT concerns and remain
unit-testable.

Pass 4d-followup: addresses Shopify Partner App approval blocker
"Settings → Data & Privacy page not built" (see
``docs/guides/SHOPIFY_PARTNER_APP_APPROVAL_READINESS.md`` §4).
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ospra_os.auth.jwt_auth import get_current_user, get_db
from ospra_os.database import User
from ospra_os.database.store_models import Store
from ospra_os.security.gdpr import (
    export_customer_data,
    redact_customer_data,
    redact_shop_data,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/account", tags=["Account / Data & Privacy"])


# ---------------------------------------------------------------------------
# Request models
# ---------------------------------------------------------------------------

class DataDeleteRequest(BaseModel):
    """
    Body for ``POST /api/account/data-delete``.

    ``confirm_email`` is a small "type your email to confirm" guard against
    accidental double-clicks — Shopify's reviewers test the page; if it
    deletes immediately on click, that's a UX-quality flag.
    """
    confirm_email: str
    delete_connected_stores: bool = True


# ---------------------------------------------------------------------------
# GET /data-summary
# ---------------------------------------------------------------------------

@router.get("/data-summary")
async def data_summary(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Cheap counts of what we hold for this user. Renders above the export /
    delete buttons so users know what they're acting on.
    """
    stores = db.query(Store).filter(Store.user_id == current_user.id).all()
    store_summaries = [
        {
            "id": s.id,
            "store_name": s.store_name,
            "platform": s.platform.value if s.platform else "unknown",
            "is_active": bool(s.is_active),
        }
        for s in stores
    ]

    # Use the export function as the authoritative record-counter — that's
    # the same code path Shopify hits for ``customers/data_request``, so
    # the number we show here will match the export the user downloads.
    export = export_customer_data(
        db,
        customer_email=current_user.email,
        shop_domain="<self-serve>",  # not a Shopify-driven request
    )

    return {
        "user": {
            "id": current_user.id,
            "email": current_user.email,
            "tier": getattr(current_user.subscription_tier, "value", None),
        },
        "stores": store_summaries,
        "store_count": len(store_summaries),
        "record_counts": export["summary"],
        "what_we_store": [
            "Your account email and tier.",
            "Email follow-ups generated by Ospra against your inbox.",
            "Order history snippets (order ID, status, customer email).",
            "OAuth tokens for any connected store (encrypted at rest).",
        ],
        "what_we_dont_store": [
            "Credit card or bank account numbers.",
            "Customer shipping addresses or phone numbers.",
            "Plaintext passwords (we store only bcrypt hashes).",
        ],
        "retention_summary": {
            "post_disconnect": "30 days, then redacted via shop/redact webhook",
            "inference_logs": "7 days rolling",
            "audit_logs": "retained for compliance — never auto-deleted",
        },
    }


# ---------------------------------------------------------------------------
# GET /data-export
# ---------------------------------------------------------------------------

@router.get("/data-export")
async def export_my_data(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Self-serve customers/data_request equivalent.

    Returns the same JSON shape the GDPR webhook handler queues for
    Shopify-driven requests, so a single audit-log row in
    ``security_audit_logs`` covers both paths.
    """
    payload = export_customer_data(
        db,
        customer_email=current_user.email,
        shop_domain="<self-serve>",
    )
    return payload


# ---------------------------------------------------------------------------
# POST /data-delete
# ---------------------------------------------------------------------------

@router.post("/data-delete")
async def delete_my_data(
    body: DataDeleteRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    Self-serve customers/redact (+ optional shop/redact) equivalent.

    The request body's ``confirm_email`` must match the signed-in user's
    email exactly — not a security boundary (the JWT already authorizes
    the call) but a UX guard so a stray click can't nuke the account.

    Note on prohibited actions: this endpoint deliberately does **not**
    delete the ``users`` row. Account deletion is a Shopify-prohibited
    operation when initiated by an automated agent — the user must take
    that step themselves through the support flow. We delete the data we
    hold *about* them; the empty user record is removed by support after
    a manual confirmation.
    """
    # UX confirm
    if (body.confirm_email or "").strip().lower() != (current_user.email or "").strip().lower():
        raise HTTPException(
            status_code=400,
            detail="Confirmation email does not match your account email.",
        )

    deletion_summary = {
        "customer": None,
        "stores": [],
    }

    # 1. Customer-scoped data (follow-ups, orders that carry this email)
    deletion_summary["customer"] = redact_customer_data(
        db,
        customer_email=current_user.email,
        shop_domain="<self-serve>",
    )

    # 2. Connected stores — only if the user opted in. Each store is wiped
    #    individually so the audit log records *which* shop the user
    #    pulled the cord on.
    if body.delete_connected_stores:
        stores = db.query(Store).filter(Store.user_id == current_user.id).all()
        for store in stores:
            shop_domain = (
                store.credentials.get("shop_url")
                if isinstance(store.credentials, dict)
                else None
            ) or store.store_url
            try:
                deletion_summary["stores"].append(
                    redact_shop_data(db, shop_domain=shop_domain)
                )
            except Exception as exc:
                logger.exception("Self-serve shop/redact failed for store %s", store.id)
                deletion_summary["stores"].append({
                    "action": "shop/redact",
                    "target": shop_domain,
                    "errors": [str(exc)],
                })

    return {
        "success": True,
        "message": (
            "Your data has been deleted. Audit-log entries are retained for "
            "compliance. To remove your account record itself, contact "
            "support@ospra.os."
        ),
        "summary": deletion_summary,
    }
